name: KafkaMap Build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  kafka-map-build:
    name: KafkaMap Build
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Private Actions Checkout
        uses: actions/checkout@v2.3.4
      - name: node Setup
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install
        run: |
          cd web
          npm install --global yarn
          yarn
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: |
          sh build.sh
          mkdir kafka-map
          cp target/kafka-map*.jar kafka-map/kafka-map.jar
          cp src/main/resources/application.yml kafka-map/application.yml
          tar zcvf kafka-map.tar.gz kafka-map/
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: kafka-map.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
